services:

  postgres:
    image: postgres:18

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: testdb

    volumes:
      - postgres-data:/var/lib/postgresql

    networks:
      - crud-network

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d testdb"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

    ports:
      - "5432:5432"


  spring-app:
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/testdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin

    ports:
      - "8080:8080"

    networks:
      - crud-network

    depends_on:
      postgres:
        condition: service_healthy


volumes:
  postgres-data:
    name: crud-app-volume


networks:
  crud-network:
    name: crud-app-nw