## First Phase BUILD PHASE

## PULL BASE IMAGE OF OPEN JDK 21 FROM REGISTERY
FROM eclipse-temurin:21-jdk AS build
## CREATE A WORKING DIRECTORY FOR THE IMAGE / CONTAINER
WORKDIR /app
## COPY ALL THE BUILD ARTIFACTS FROM HOST TO WORK DIRECTORY
COPY pom.xml pom.xml
COPY mvnw mvnw
COPY .mvn .mvn
## DOWNLOAD THE MAVEN DEPENDECIES
RUN ./mvnw dependency:go-offline
## COPY SOURCE CODE INTO WOEK DIR
COPY src src
## BUILD THE SOURCE CODE
RUN ./mvnw clean package -DskipTests

## SECOND PHASE RUN PHASE
FROM eclipse-temurin:21-jre AS run
## CREATE WORK DIR / CONTINUE FROM SAME WORK DIR
WORKDIR /app
## COPY THE BUILD ARTIFACT / JAR FILE FROM The BUILD PHASE
COPY --from=build ./app/target/*.jar app.jar
## MENTION THAT THE APP EXPOSE THE PORT
EXPOSE 8080
## DEFAULT RUN COMMAND FOR CONTAINER
CMD ["java" , "-jar" , "app.jar"]


